const ENUM_ROLE = {
	ADMIN: 2,
	STAFF: 1,
	USER: 0,
	BAN: -1,
};
const ENUM_APARTMENT_TYPE = {
	SHARE_ROOM: 1,
	FOR_RENT: 2,
};
const ENUM_APARTMENT_CATEGORIES = {
	APARTMENT: 1,
	HOUSE: 2,
	BOARDING_HOUSE: 3,
};
const ENUM_RENT_REQUEST = {
	PENDING: 0,
	ACCEPTED: 1,
	REJECTED: -1,
	CANCEL: -2,
};
const ENUM_STATUS_TICKET = {
	PENDING: 0,
	DONE: 2,
	REPLYING: 1,
	REJECTED: -1,
	CANCEL: -2,
};
const ENUM_COMMENT = {
	PENDING: 0,
	APPROVED: 1,
	REJECTED: -1,
};
const ENUM_STATUS_APARTMENT = {
	PENDING: 0,
	BLOCK: 1,
	ACTIVE: 2,
	IS_VERIFIED: 3,
};
const ENUM_STATUS_VERIFY_APARTMENT = {
	PENDING: 0,
	DONE: 1,
	REJECTED: -1,
};
const ENUM_ORDER = {
	PENDING: 0,
	SUCCESS: 1,
	FAILED: -1,
};
const ENUM_PRIORY = {
	DEFAULT: 0,
	LOW: 1,
	MEDIUM: 2,
	HIGH: 3,
	EXTRA: 4,
};
const ENUM_PRICE_PRIORITY = {
	[ENUM_PRIORY.DEFAULT]: 20000, // with default priority, for lifetime
	[ENUM_PRIORY.LOW]: 5000, // per 1 day
	[ENUM_PRIORY.MEDIUM]: 10000, // per 1 day
	[ENUM_PRIORY.HIGH]: 15000, // per 1 day
	[ENUM_PRIORY.EXTRA]: 20000, // per 1 day
};
const ENUM_STRING_PRIORY = {
	[ENUM_PRIORY.DEFAULT]: "Tin thường",
	[ENUM_PRIORY.LOW]: "Đồng",
	[ENUM_PRIORY.MEDIUM]: "Bạc",
	[ENUM_PRIORY.HIGH]: "Vàng",
	[ENUM_PRIORY.EXTRA]: "Kim cương",
};
const ENUM_TYPE_ORDER = {
	PAY_FOR_APARTMENT: 1,
	PAY_FOR_BOOST: 2,
	PAY_FOR_VERIFY_APARTMENT: 3,
};
const AMOUNT_FOR_VERIFY_APARTMENT = 100000;

module.exports = {
	ENUM_ROLE,
	ENUM_RENT_REQUEST,
	ENUM_STATUS_TICKET,
	ENUM_COMMENT,
	ENUM_APARTMENT_TYPE,
	ENUM_APARTMENT_CATEGORIES,
	ENUM_STATUS_APARTMENT,
	ENUM_ORDER,
	ENUM_PRIORY,
	ENUM_PRICE_PRIORITY,
	ENUM_STRING_PRIORY,
	ENUM_TYPE_ORDER,
	ENUM_STATUS_VERIFY_APARTMENT,
	AMOUNT_FOR_VERIFY_APARTMENT,
};
